### ISSUE TITLE
US 01.06.01 - Add Editing Functionality to Book Display

### ISSUE THREAD

**Issue by ArthurChan0427** [CMPUT301F20T34/Bookworm#27]
**Partial User Story:**
As an owner, I want to view and edit a book description in my books.

**Rationale:**

- Book descriptions may be changed or the initial entries may be incorrect. The owner may want to change them in these cases.

**Story Points:**
1

**Risk Level:**
low

**Comment by HarrisonFah** [comment]
I think the rationale can be changed to "The books description may be changed or the owner entered it wrong, thus they may want to change it.". I think you can also remove the "user interface needs to allow for this task"
