### ISSUE TITLE
US 01.07.01 - Add Deleting Functionality to Book Display

### ISSUE THREAD

**Issue by ArthurChan0427** [CMPUT301F20T34/Bookworm#29]
**Partial User Story:**
As an owner, I want to delete a book in my books.

**Rationale:**

- If an owner loses ownership of a book they will want to remove it from their collection

**Story Points:**
1

**Risk Level:**
low

**Comment by HarrisonFah** [comment]
I think the rationale may be able to be changed to something like "If an owner loses ownership of a book they will want to remove it from their collection.". I don't think the "user interface needs to allow for this task" needs to be written.
